### ISSUE TITLE
Changes to `lectures.quantecon.org` page

### ISSUE THREAD

**Issue by jstac** [QuantEcon/website#11]
@DrDrij this is from my email, just helping us keep track of what needs to be done:

I think I've gone a bit overboard with all the Sloan badges. On this page it eats up too much space:

https://quantecon.org/lectures/

Would be able to strip it out, as well as the QuantEcon badge?

**Comment by DrDrij** [comment]
- Sponsor badges removed from lectures page
- Added section to homepage with sponsor badges, heading "Sponsors"
- Section includes ANU and Sloan

https://github.com/QuantEcon/website/pull/12
