### ISSUE TITLE
Review and Update QuantEcon Org Site

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/website#123]
It is time to do a refresh of the QuantEcon organization site (Many of these are suggestions by @thomassargent30)

- [x] improve visibility of current QuantEcon sponsors
- [x] reduce visibility of former sponsors
- [x] update team page and ensure pictures for everyone and improve default avatars.
- [x] review news page to make more relevant and keep it up to date (monthly). 

**Discussion:**

- [x] Remove some information from the front page such as old "Working from QuantEcon" information and rely on the `Team` page

**Comment by mmcky** [comment]
@DrDrij what is your schedule like. Would you have a few hours to help me make some adjustments to the org site? I would go through and make some markups on screenshots if you do to explain the changes.

**Comment by DrDrij** [comment]
Can do @mmcky, possible to chat after 5pm one day this week?

**Comment by mmcky** [comment]
Closing as most of these have been done.
