### ISSUE TITLE
Workshop - Add Abstract / blurb on what the workshop was about

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/website#133]
@jstac reported

Perhaps each one should have an abstract copy pasted from the GH page?

@mmcky to improve the workshop pages with additional information.

**Comment by DrDrij** [comment]
@jstac Pulled abstract as suggested into blockquotes. Passable?

@mmcky I have done roughly the first 15 workshops. Worth doing all of them?

![image](https://github.com/user-attachments/assets/28fb86fe-75f0-46a9-a9cb-45533d9228b2)

**Comment by mmcky** [comment]
thanks @DrDrij. Just a couple of comments:

1. I wonder if we should adopt a similar style to the news page with the date information in a LHS column. I think that looks pretty nice. 
2. I think we should delete `Workshops and Seminars` and keep the header highlighted as an indicator of the page to reduce duplication
3. I think we should delete `Recent Workshops` to reduce duplication.
