### ISSUE TITLE
Increase visibility to Discourse Forum

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/website#134]
@jstac commented

Also, where are the links to the forum on the org pages or lecture pages?  Should we increase the visibility?

@DrDrij as we are doing with GitHub (turning text into the icon) and I think we should also have the discourse icon next to it with hover text (QuantEcon Forum)

**Comment by DrDrij** [comment]
@jstac Let me know if the icon sucks, but good idea to bring up Discourse.

<img width="629" alt="image" src="https://github.com/user-attachments/assets/6d82021d-f494-4b47-aae7-0ef31fa57a0a">
