### ISSUE TITLE
Add a new textbook project page

### ISSUE THREAD

**Issue by jstac** [QuantEcon/website#18]
As previously mentioned, @thomassargent30 and I are writing a hardcopy text, with support from Schmidt Futures.  Could someone please add a new "project" page with a suitable icon, visible in the projects section of the top page?  The order doesn't matter very much.

Title is "QuantEcon textbook".

We'll use the page to offer a download to the working versions of the document and thank Schmidt Futures.  I can do this.

CC @DrDrij @mmcky --- please feel free to delegate.

**Comment by DrDrij** [comment]
@jstac Do we have a link that the project will link to?

**Comment by jstac** [comment]
The icon will link to a new page on the same site.  Similar to, say, https://quantecon.org/workshops/.

I can fill in the text if the rest is created for me.  Thanks @DrDrij

**Comment by mmcky** [comment]
@DrDrij I will leave this with you but sing out if you need me to have input on this.

**Comment by DrDrij** [comment]
Hey @jstac this project page icon have been added. The project page requires a little content, you can edit the page here: https://github.com/QuantEcon/website/edit/master/_projects/textbook.md

@mmcky Could you please do a rebuild of quantecon.org? Matt, what do you think about switching to immediate rebuild and publishing of the quantecon.org site (using Netlify)? Anything holding this back?

![image](https://user-images.githubusercontent.com/5886045/79099276-214e2000-7da7-11ea-95cf-5baa99c66e64.png)

**Comment by jstac** [comment]
Thanks @DrDrij, much appreciated.

**Comment by mmcky** [comment]
that looks nice @DrDrij
