### ISSUE TITLE
Improve get involved page

### ISSUE THREAD

**Issue by jstac** [QuantEcon/website#2]
CC @mmcky @DrDrij @duncanhobbs @shizejin 

It would be great if we could improve this page so that we can just point new RAs to it, as well as people who are starting to put in PRs remotely: 

https://quantecon.org/get-involved/

It could have a quick summary of all the essential information you need to get started editing the lectures and putting in PRs.

Eg:

* you need to know how to use git and GH -- link ot GH's tutorial page?
* basic information on how the lectures are compiled from rst files.
* how to build the rst files into the lectures using Jupinx.

Also, we should have common conventions.  

Eg:

* If possible, a PR should address just one lecture.
* Python lectures should execute with the latest version of Anaconda.

We should avoid adding excess information that needs to be maintained.  (Eg, let's not tell people how to make a PR --- just point them to a GH tutorial if necessary.  Let's not tell them how to use Jupinx --- just point them to the website.)

(Might one of the CCed people be able to help out?)

**Comment by jstac** [comment]
Note: some improvements already made in merged PR #3 but let's look over this again in a month or two.

**Comment by DrDrij** [comment]
Note: @mmcky alerted the fact the `/contribute/` and `/get-involved/` were duplicate pages with the same H1 "Get Involved". In the following PR I've merged them into a single `contribute.md`. I chose this over `get-involved` as we have "Contribute" in the primary navigation. The main heading remains "Get Involved".

https://github.com/QuantEcon/website/pull/6

@jstac Would you prefer it the other way around? (Having "Get Involved" in the primary navigation, replacing "Contribute")

**Comment by jstac** [comment]
This is fine, thanks @DrDrij

**Comment by mmcky** [comment]
Closing as old issue - and will review in the `site-review` project.
