### ISSUE TITLE
Issue with Gemfile

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/website#29]
It seems there is an issue with the current [Gemfile](https://github.com/QuantEcon/website/blob/master/Gemfile). 

Logs for the [build](https://github.com/QuantEcon/website/runs/676998845?check_suite_focus=true)

**Comment by HengchengZhang** [comment]
Hi @mmcky, is there any error log I can find related to this?

**Comment by mmcky** [comment]
Current builds are working OK via github actions and netlify. Closing.
