### ISSUE TITLE
BUG: Menubar Small Icons out of Alignment (on initial load of page)

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/website#4]
The menubar on `initial` load places small `basket`, `twitter` icons out of line. 

![image](https://user-images.githubusercontent.com/8263752/67177349-eaabd400-f419-11e9-882e-dc8c0dc687a4.png)

@DrDrij I know this is a known issue. Just documenting here.

**Comment by DrDrij** [comment]
Applied a fix. However I'd like to revisit the menubar as it could be implemented in a better way.

**Comment by DrDrij** [comment]
This is no longer an issue as a new menubar has been rolled out.
