### ISSUE TITLE
Migrate to Github Pages

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/website#42]
We should migrate the hosting of the `quantecon.org` website to `github pages`

**Comment by DrDrij** [comment]
@mmcky This has been completed.
- Pages enabled on `website` repo
- CNAME added to repo
- Route53 AWS changed A record to point to GitHub Pages

**Comment by mmcky** [comment]
@DrDrij this is awesome. Thanks 🥳

**Comment by mmcky** [comment]
This is using `jekyll` too right so we don't need to build anything with github actions now?

**Comment by DrDrij** [comment]
> This is using `jekyll` too right so we don't need to build anything with github actions now?
> 
> 

Yup!

**Comment by mmcky** [comment]
hey @DrDrij it still looks like this is building to AWS

https://github.com/QuantEcon/website/blob/master/.github/workflows/build-and-deploy.yml

Am I missing something?

Also there is no `gh-pages` branch

**Comment by mmcky** [comment]
Oh I see I think it's just pointing to master 👍 

Feel free to close this when convenient.
