### ISSUE TITLE
Update links in _team-members

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/website#55]
There are several missing links in [_team-members](https://github.com/QuantEcon/website/tree/master/_team-members).

**Comment by mmcky** [comment]
@DrDrij let's review the team page as part of our `site-refresh` project (i.e. improved default image when no photo is included). 

As part of this @mmcky needs to review links.

**Comment by DrDrij** [comment]
Updated any team member link that was broken.
Added avatars/photos to all that were missing one.
