### ISSUE TITLE
Improve Hard Copy Textbooks Page

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/website#72]
Perhaps when we meet with Andrij in early Jan we could have a page / textbook (with description and TOC) and a whole landing page for all Textbooks that are in the works?

**Comment by DrDrij** [comment]
@mmcky Sounds good. Lets dress up the textbook page, perhaps with a screenshot of the 'networks' book site. It's so pretty.

**Comment by mmcky** [comment]
Closing this as an old issue.
