### ISSUE TITLE
New image for org site

### ISSUE THREAD

**Issue by jstac** [QuantEcon/website#74]
I must be getting old because I've started to prefer light, uplifting images instead of dark forboding ones.

I know I suggested the current image on the org site but could we please look at some other options now?

How about the one at https://twitter.com/QuantEcon ?  Let's discuss.

**Comment by jstac** [comment]
We could also use an AI image generator such as dall-e 2.  Somehow that seems appropriate.

(This issue addresses the new org site under construction by @DrDrij )

**Comment by DrDrij** [comment]
DALL-E with string: 'A hero area image for a website about quantitative economics. Appealing, sci-fi, light artistic style.'

![image](https://user-images.githubusercontent.com/5886045/211241474-535dcdaf-cc91-484c-8631-64cc74b7e5fe.png)

Twitter background image:

![image](https://user-images.githubusercontent.com/5886045/211446657-79b8e461-36ec-4e96-88e5-1494aa241a73.png)

**Comment by natashawatkins** [comment]
@DrDrij is there something that could generate an AI version of that Montana pic? I think I just got that off a random google search years ago

**Comment by jstac** [comment]
Thanks!  I'm not sure about the Dall-E ones but I like the Montana one --- and Tom will probably like it too...

**Comment by DrDrij** [comment]
![image](https://user-images.githubusercontent.com/5886045/211967244-c2ae3851-cf37-4d6a-a4aa-aa0963cdf798.png)


![image](https://user-images.githubusercontent.com/5886045/211967298-7480268e-6cd2-453e-9383-3779b2ade0a0.png)

**Comment by jstac** [comment]
Nice!  I think I like the first one.  

@thomassargent30 has just arrived in town (the eagle has landed) so we can all get together in a meeting next week and figure out what we like best.
