### ISSUE TITLE
Add an advertisement for a new predoc

### ISSUE THREAD

**Issue by jstac** [QuantEcon/website#78]
Relevant quote from email chain:

> > How about an ad on our org site?
>
> The main issue with this is that we often get a lot of interest from overseas.
>
> We can specify Australia based only -- so can't hurt right?

That's what I was thinking --- we need to specify Aus work rights.

It would be good to generate some interest and get a range of applicants.

What's the best way to get this done?  I have a feeling we need to run
this via ANU HR as well as putting the ad up on the QE website.

**Comment by DrDrij** [comment]
How about a button on the homepage + seperate page with details as below?
Alternatively we can create an additional section on the homepage and have all the details there with a contact link.

![image](https://user-images.githubusercontent.com/5886045/211240699-7b7ac09a-b094-4155-853d-a0d805634db6.png)

**Comment by mmcky** [comment]
> How about a button on the homepage + seperate page with details as below? Alternatively we can create an additional section on the homepage and have all the details there with a contact link.
> 
> ![image](https://user-images.githubusercontent.com/5886045/211240699-7b7ac09a-b094-4155-853d-a0d805634db6.png)

thanks @DrDrij. Is it possible to add a short term "banner type" announcement? I like the above idea also.

**Comment by jstac** [comment]
Thanks @DrDrij , nice work.  We could combine this with a news item.  

How about a more generic "See available positions" which leads to a page titled "Current positions".

At minimum we are usually always seeking RAs at ANU, so it seems like a good idea to have a permanent page up.  (Worst, case, we can simply put "None currently available".)

**Comment by DrDrij** [comment]
Super, thanks for the feedback.

We now have a page for positions.

![image](https://user-images.githubusercontent.com/5886045/211963060-504fcccc-5f69-48db-a73d-503880afbf8e.png)


With a link in the footer.

![image](https://user-images.githubusercontent.com/5886045/211963101-db20a950-b5da-4f23-8241-0a2fc22e70f9.png)

And button on homepage.

![image](https://user-images.githubusercontent.com/5886045/211963160-8a74132c-8346-49b5-8ec9-3acc14fd7493.png)
