### ISSUE TITLE
Add button to past workshops

### ISSUE THREAD

**Issue by jstac** [QuantEcon/website#84]
Perhaps add a button on the top page, next to "Contact Us" in the workshops section that has text "Past workshops" and links to https://quantecon.org/workshops/

**Comment by mmcky** [comment]
@DrDrij currently this page is linked just by some within page text. We should make this more discoverable in the refresh.

**Comment by DrDrij** [comment]
Ok, I've added it to the navigation so we have the link. Depending on feedback I can move it going forward.

![image](https://github.com/user-attachments/assets/da380f63-618b-4b08-ae27-f6e8e2592969)

**Comment by DrDrij** [comment]
Addressed in this PR: https://github.com/QuantEcon/website/pull/121
