### ISSUE TITLE
[lecture-python-intro] Launch of Undergraduate Website

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/website#89]
- [x] setup a news item for the launch of `intro.quantecon.org`

![hackathon-photo1](https://user-images.githubusercontent.com/8263752/231057491-491077fe-6352-4b8a-93e2-863654d104c3.jpg)

this photo is from the initial writing sprint workshop.

**Comment by natashawatkins** [comment]
@mmcky should I write this news item? I haven't heard much about the project.

**Comment by mmcky** [comment]
thanks @natashawatkins once we go live I will update you. Should be in the next week or two.

**Comment by mmcky** [comment]
@natashawatkins we are targeting to go live around 5th June. It's a new lecture series targeting undergraduates.

**Comment by mmcky** [comment]
This was done. Closing.
