### ISSUE TITLE
Books need higher visibility

### ISSUE THREAD

**Issue by DrDrij** [QuantEcon/website#94]
The books are https://dp.quantecon.org/ and https://networks.quantecon.org/

We have invested a lot of time and effort into them and they need to be easily accessible from the top page.

- Suggested add to Lectures and Code just below the hero area on the homepage

**Comment by DrDrij** [comment]
Working on this one, have created thumbnails and just playing around with layout.

@jstac Any immediate thoughts on this mockup?

<img width="1279" alt="image" src="https://github.com/QuantEcon/website/assets/5886045/8c5246a7-ea24-4590-b768-e481718d076f">

**Comment by jstac** [comment]
Thanks @DrDrij , you have a great eye.  They look beautiful.

**Comment by DrDrij** [comment]
Hi Team, here are the image assets incase someone else has a crack at it.



![Image](https://github.com/QuantEcon/website/assets/5886045/50637887-b167-4599-b142-74cf4e077cbb)
![Image](https://github.com/QuantEcon/website/assets/5886045/a73229d2-8c57-4b35-ab26-42a8e8d0624c)

**Comment by jstac** [comment]
@HengchengZhang , are you and @Jingni0117 working on this?

**Comment by HengchengZhang** [comment]
Hi @jstac, we are not designing the layout of this page cause we thought Andrij is doing this.

But we will add this page to the website once this is merged.

**Comment by jstac** [comment]
I think @DrDrij is passing the baton to you by handing over the designs above, @HengchengZhang .   Please coordinate with other teammates to try to get this done -- or if you can't (which I understand) then let us know.  

(But this job has to get done one way or another.)

**Comment by HengchengZhang** [comment]
Hi @jstac, yeah sure I will take care of this.

**Comment by DrDrij** [comment]
> Working on this one, have created thumbnails and just playing around with layout.
> 
> @jstac Any immediate thoughts on this mockup?
> 
> <img alt="image" width="1279" src="https://private-user-images.githubusercontent.com/5886045/242269683-8c5246a7-ea24-4590-b768-e481718d076f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjM0OTUsIm5iZiI6MTczMzM2MzE5NSwicGF0aCI6Ii81ODg2MDQ1LzI0MjI2OTY4My04YzUyNDZhNy1lYTI0LTQ1OTAtYjc2OC1lNDgxNzE4ZDA3NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMDE0NjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc0MjI1MWYzMzYwNjYxNWZiNmQ3YTU3NDlmMjlhMWU3Mjc1OTRlODgzNWQyYzZkMTM3MmZjZDUyMmE2M2E0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fPb9CkdbWUdNc3-srkYj97CD2Q9gdqiRjGsFPqZRi1Q">

These are looking pretty good where they are on the homepage, links working. @mmcky please reopen if the books should be given more focus.
