### ISSUE TITLE
Update news and teams page

### ISSUE THREAD

**Issue by HengchengZhang** [QuantEcon/website#95]
Work with @Jingni0117:

News:
- [x] workshops (1 news)
- [x] textbook (2 news)

Projects/workshops and seminars:
- [x] workshops (3 with links respectively)

Teams:
- [x] ask Humphrey and Smit for a brief self description 
- [x] add them to lead developer
- [x] remove chase to previous one
- [x] add J and Andrj to design and marketing 

Homepage:
- [ ] workshops locations should be consistent. Either cities or universities. Add new ones 
- [x] https://github.com/QuantEcon/website/issues/94#issue-1723176576
- [ ] update tool bar

Update : Team/ QuantEcon Early Career Researchers

cc: @jstac

**Comment by HengchengZhang** [comment]
Hi @mmcky, do we have an instruction on how to preview any staged changes?

I tried to open the html file directly in my browser but this doesn't work.

Many thanks :D

**Comment by mmcky** [comment]
@HengchengZhang there are no preview builds on the `website`. 

You can build locally using `Jekyll`

https://jekyllrb.com

and there are some quick start instructions there for the page to be served on your system.

**Comment by HengchengZhang** [comment]
Thank a lot @mmcky! I will have a look now.

**Comment by mmcky** [comment]
@HengchengZhang once you get up and running maybe you can

- [ ] add a page to QuantEcon.manual for building the `website` locally.

**Comment by mmcky** [comment]
Closing as mostly implemented and remaining issues are documented in other items for the upcoming `site-refresh`
