### ISSUE TITLE
Team page broken

### ISSUE THREAD

**Issue by HengchengZhang** [QuantEcon/website#97]
Hi @DrDrij and @jstac, I just randomly noticed that the team page is broken https://quantecon.org/team/

**Comment by jstac** [comment]
Thanks @HengchengZhang , nice catch!  @DrDrij , could this be caused by your last commit?

**Comment by DrDrij** [comment]
Thanks both. Team page was merged into the About page. I need to remove it from the navigation.

**Comment by DrDrij** [comment]
Fixed the navigation bug. See About page for Team content.
